version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]

  - name: dim_accounts
    columns:
      - name: account_id
        tests: [unique, not_null]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: dim_merchants
    columns:
      - name: merchant_id
        tests: [unique, not_null]

  - name: dim_billers
    columns:
      - name: biller_id
        tests: [unique, not_null]

  - name: fact_transactions
    columns:
      - name: transaction_id
        tests: [unique, not_null]
      - name: account_id
        tests:
          - relationships:
              to: ref('dim_accounts')
              field: account_id
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['PENDING', 'SETTLED', 'DECLINED', 'CANCELLED']

  - name: agg_daily_revenue
    columns:
      - name: transaction_date
        tests: [unique, not_null]

  - name: agg_revenue_by_channel
    columns:
      - name: channel
        tests:
          - accepted_values:
              arguments:
                values: ['Web', 'Mobile', 'POS', 'ATM']

  - name: agg_revenue_by_type
    columns:
      - name: transaction_type
        tests:
          - accepted_values:
              arguments:
                values: ['purchase', 'bill_payment', 'transfer']